// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn8Ep7cOwXoAPliiOd_WyE3ILBp9Mt7Rc',
    appId: '1:1046753209619:web:091f5c6d51f2b791283ee6',
    messagingSenderId: '1046753209619',
    projectId: 'chat-app-ea642',
    authDomain: 'chat-app-ea642.firebaseapp.com',
    storageBucket: 'chat-app-ea642.firebasestorage.app',
    measurementId: 'G-P3Z4LQ0STQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgcdY6XXAgchdugU0AYUUIduUf2rdU5nA',
    appId: '1:1046753209619:android:a0fb387d11a263d0283ee6',
    messagingSenderId: '1046753209619',
    projectId: 'chat-app-ea642',
    storageBucket: 'chat-app-ea642.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa_eEppqiFLzaqVZ3AA80dCUO33uzWNyQ',
    appId: '1:1046753209619:ios:4fde06bbd0680db4283ee6',
    messagingSenderId: '1046753209619',
    projectId: 'chat-app-ea642',
    storageBucket: 'chat-app-ea642.firebasestorage.app',
    iosBundleId: 'com.example.servix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa_eEppqiFLzaqVZ3AA80dCUO33uzWNyQ',
    appId: '1:1046753209619:ios:4fde06bbd0680db4283ee6',
    messagingSenderId: '1046753209619',
    projectId: 'chat-app-ea642',
    storageBucket: 'chat-app-ea642.firebasestorage.app',
    iosBundleId: 'com.example.servix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn8Ep7cOwXoAPliiOd_WyE3ILBp9Mt7Rc',
    appId: '1:1046753209619:web:f6d0d8a167e54dea283ee6',
    messagingSenderId: '1046753209619',
    projectId: 'chat-app-ea642',
    authDomain: 'chat-app-ea642.firebaseapp.com',
    storageBucket: 'chat-app-ea642.firebasestorage.app',
    measurementId: 'G-3WD2EJ1HGC',
  );
}
